#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

source "$HOME/.config/sketchybar/colors.sh"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=34 \
    color=$BAR_COLOR \
    margin=0 \
    sticky=on \
    padding_left=23 \
    padding_right=23 \
    notch_width=188 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=$BLACK \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=$WHITE \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event aerospace_workspace_change

sketchybar --add item current_space left \
    --set current_space \
    background.color=$YELLOW \
    icon.color=$BLACK \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change aerospace_workspace_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=$GREEN \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=0 \
    icon.color=$BLACK \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.name left \
    --set front_app.name \
    background.color=$BLACK \
    background.padding_right=3 \
    background.padding_left=0 \
    label.font="$FONT_FACE:Bold:12.0" \

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.name \
    --subscribe front_app front_app_switched workspace_change

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=$RED \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item        cpu.percent right             \
           --set cpu.percent label.font="$FONT_FACE:Bold:12"   \
                             label=CPU                     \
                             y_offset=0                    \
                             width=40                      \
                             icon.drawing=off              \
                             update_freq=2                 \
                             background.padding_right=10   \
           --add graph       cpu.user right 100            \
           --set cpu.user    graph.color=$BLUE             \
                             update_freq=2                 \
                             label.drawing=on             \
                             icon.drawing=on                \
                             icon.color=$BLUE                 \
                             icon=                         \
                             background.padding_right=3   \
                             background.color=$BLACK        \
                             script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item        memory.percent right             \
           --set memory.percent label.font="$FONT_FACE:Bold:12" \
                             label=MEMORY                       \
                             y_offset=0                     \
                             width=40                        \
                             icon.drawing=off                \
                             update_freq=2                   \
                             background.padding_right=10     \
                                                             \
           --add graph       memory.percent_usage right 100           \
           --set memory.percent_usage                        \
                             graph.color=$RED                \
                             update_freq=2                                \
                             label.drawing=off               \
                             icon.drawing=on                \
                             icon.color=$RED                 \
                             icon=                          \
                             background.padding_right=3     \
                             script="$PLUGIN_DIR/memory.sh"


sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=$BLUE \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change


##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
